name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - name: Set up .env
      run: |
        echo "${{ secrets.PROD_ENV_FILE }}" | base64 --decode > .env

    - name: Decode PEM File
      run: |
        echo "${{ secrets.PEM_FILE_BASE64 }}" | base64 --decode > auto-deploy-demo.pem
        chmod 600 auto-deploy-demo.pem

    - name: Deploy to Production
      run: |
        ssh -i 'auto-deploy-demo.pem' ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com << 'EOF'
        cd /home/ubuntu/actions-runner/_work/auto-deployment-demo
        git fetch origin
        git reset --hard origin/master
        npm ci
        # pm2 stop all || true
        # pm2 start index.js --name "auto-deployment-demo"
        pm2 reload 0
        pm2 log 0
        EOF

    - name: Monitor Production
      run: |
        ssh -i 'auto-deploy-demo.pem' ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com << 'EOF'
        curl -f http://localhost:8000 || exit 1
        EOF

    - name: Revert to Previous Stable Commit if Errors Occur
      if: failure()
      run: |
        ssh -i 'auto-deploy-demo.pem' ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com << 'EOF'
        cd /home/ubuntu/actions-runner/_work/auto-deployment-demo
        echo "Reverting to previous stable commit..."
        git fetch origin
        git reset --hard origin/master@{1} # Revert to the previous commit
        npm ci
        # pm2 stop all || true
        # pm2 start index.js --name "auto-deployment-demo"
        pm2 reload 0
        pm2 log 0
        EOF
