name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - name: Set up .env
      run: |
        echo "${{ secrets.PROD_ENV_FILE }}" | base64 --decode > .env

    - name: Decode PEM File
      run: |
        echo "${{ secrets.PEM_FILE_BASE64 }}" | base64 --decode > auto-deploy-demo.pem
        chmod 600 auto-deploy-demo.pem

    - name: Create Archive
      run: |
        mkdir temp-deploy
        cp -r ./* temp-deploy
        tar -czf auto-deployment-demo.tar.gz -C temp-deploy . || { echo "Failed to create archive"; exit 1; }
        rm -rf temp-deploy


    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: deployment-archive
        path: auto-deployment-demo.tar.gz

    - name: Deploy to Production
      run: |
        scp -i 'auto-deploy-demo.pem' auto-deployment-demo.tar.gz ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com:/home/ubuntu/actions-runner/_work/auto-deployment-demo/auto-deployment-demo.tar.gz

    - name: Stop Existing Application
      run: |
        ssh -i 'auto-deploy-demo.pem' ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com << 'EOF'
        sudo lsof -t -i:8000 | xargs -r sudo kill -9
        EOF

    - name: Deploy Application
      run: |
        ssh -i 'auto-deploy-demo.pem' ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com << 'EOF'
        cd /home/ubuntu/actions-runner/_work/auto-deployment-demo
        tar -xzf auto-deployment-demo.tar.gz
        rm auto-deployment-demo.tar.gz
        cd auto-deployment-demo
        npm ci
        PORT=8000 npm start &
        EOF

    - name: Monitor Production
      run: |
        ssh -i 'auto-deploy-demo.pem' ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com << 'EOF'
        curl -f http://localhost:8000 || exit 1
        EOF

    - name: Revert to Previous Version if Errors Occur
      if: failure()
      run: |
        ssh -i 'auto-deploy-demo.pem' ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com << 'EOF'
        BACKUP_DIR="/home/ubuntu/actions-runner/_work/auto-deployment-demo/backup"
        CURRENT_PRODUCTION="/home/ubuntu/actions-runner/_work/auto-deployment-demo/auto-deployment-demo"
        latest_backup=$(ls -dt $BACKUP_DIR/production-* | head -1)
        [ -d "$latest_backup" ] && rm -rf $CURRENT_PRODUCTION && cp -r "$latest_backup" $CURRENT_PRODUCTION || { echo "No backup found"; exit 1; }
        EOF
