name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
    
    - name: Run Tests
      run: npm test
    
    - name: Set up .env
      run: |
        echo "${{ secrets.PROD_ENV_FILE }}" | base64 --decode > .env
    
    - name: Decode PEM File
      run: |
        echo "${{ secrets.PEM_FILE_BASE64 }}" | base64 --decode > auto-deploy-demo.pem
        chmod 600 auto-deploy-demo.pem

    - name: Verify Directory Structure
      run: |
        echo "Current directory:"
        pwd
        echo "Listing contents:"
        ls -la

    - name: Upload Artifact for Debugging
      uses: actions/upload-artifact@v3
      with:
        name: deployment-directory
        path: .  # Path to the current directory

    - name: Deploy to Production
      run: |
        SCP_PATH="/home/ubuntu/actions-runner/_work/auto-deployment-demo/auto-deployment-demo"
        echo "Using SCP path: $SCP_PATH"
        if [ -d "$SCP_PATH" ]; then
          echo "Directory exists. Proceeding with SCP."
          scp -i 'auto-deploy-demo.pem' -r . ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com:/home/ubuntu/actions-runner/_work/auto-deployment-demo/auto-deployment-demo
        else
          echo "Directory does not exist. Please check the path."
          exit 1
        fi

    - name: Install Dependencies on Production
      run: |
        ssh -i 'auto-deploy-demo.pem' ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com << 'EOF'
        cd /home/ubuntu/actions-runner/_work/auto-deployment-demo/auto-deployment-demo
        npm ci
        npm start &  # Run the application in the background
        sleep 10  # Wait for 10 seconds to give the application time to start
        EOF

    - name: Monitor Production for Errors
      run: |
        ssh -i 'auto-deploy-demo.pem' ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com << 'EOF'
        # Check application status (replace with actual check)
        if curl -f http://localhost:8000; then
          echo "Deployment successful"
        else
          echo "Deployment failed"
          exit 1
        fi
        EOF

    - name: Revert to Previous Production Version if Errors Occur
      if: failure()
      run: |
        ssh -i 'auto-deploy-demo.pem' ubuntu@ec2-65-0-193-48.ap-south-1.compute.amazonaws.com << 'EOF'
        # Define absolute paths
        BACKUP_DIR="/home/ubuntu/actions-runner/_work/auto-deployment-demo/backup"
        CURRENT_PRODUCTION="/home/ubuntu/actions-runner/_work/auto-deployment-demo/auto-deployment-demo"

        # Find the latest backup
        latest_backup=$(ls -dt $BACKUP_DIR/production-* | head -1)

        # Revert to the latest backup
        if [ -d "$latest_backup" ]; then
          rm -rf $CURRENT_PRODUCTION
          cp -r "$latest_backup" $CURRENT_PRODUCTION
          echo "Reverted to backup: $latest_backup"
        else
          echo "No backup found to revert to"
          exit 1
        fi
        EOF
